"""Changed weather model datatype on rain and snow fields

Revision ID: 05d253cd8102
Revises: dad31c569456
Create Date: 2023-07-28 20:39:05.781387

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05d253cd8102'
down_revision = 'dad31c569456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'rain',
                    existing_type=sa.VARCHAR(length=25),
                    type_=sa.JSON(),
                    existing_comment='Units: mm',
                    existing_nullable=True,
                    postgresql_using='rain::json')
    op.alter_column('weather', 'snow',
                    existing_type=sa.VARCHAR(length=25),
                    type_=sa.JSON(),
                    existing_comment='Units: mm',
                    existing_nullable=True,
                    postgresql_using='snow::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'snow',
                    existing_type=sa.JSON(),
                    type_=sa.VARCHAR(length=25),
                    existing_comment='Units: mm',
                    existing_nullable=True)
    op.alter_column('weather', 'rain',
                    existing_type=sa.JSON(),
                    type_=sa.VARCHAR(length=25),
                    existing_comment='Units: mm',
                    existing_nullable=True)
    # ### end Alembic commands ###
