"""Added Weather model

Revision ID: c1e89a30fe5e
Revises: fb6cec490ff1
Create Date: 2023-06-13 21:18:50.980291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e89a30fe5e'
down_revision = 'fb6cec490ff1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('weather_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('temp', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=True, comment='Units: Celsius'),
    sa.Column('temp_min', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=True, comment='Units: Celsius'),
    sa.Column('temp_max', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=True, comment='Units: Celsius'),
    sa.Column('pressure', sa.Integer(), nullable=True, comment='Units: hPa'),
    sa.Column('humidity', sa.Integer(), nullable=True, comment='Units: %'),
    sa.Column('visibility', sa.Integer(), nullable=True, comment='Units: meter'),
    sa.Column('wind_speed', sa.Numeric(precision=4, scale=2, asdecimal=False), nullable=True, comment='Units: meter/sec'),
    sa.Column('rain', sa.String(length=25), nullable=True, comment='Units: mm'),
    sa.Column('snow', sa.String(length=25), nullable=True, comment='Units: mm'),
    sa.Column('clouds', sa.Integer(), nullable=True, comment='Units: %'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
