"""Added City model

Revision ID: d40f260fed81
Revises: 
Create Date: 2023-06-11 20:32:32.717234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40f260fed81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=5, scale=5, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=5, scale=5, asdecimal=False), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
