"""Changed precision in City.latitude and City.longitude

Revision ID: fb6cec490ff1
Revises: c740ee99497a
Create Date: 2023-06-11 22:31:53.554116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6cec490ff1'
down_revision = 'c740ee99497a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'latitude',
               existing_type=sa.NUMERIC(precision=5, scale=5),
               type_=sa.Numeric(precision=9, scale=5, asdecimal=False),
               existing_nullable=False)
    op.alter_column('city', 'longitude',
               existing_type=sa.NUMERIC(precision=5, scale=5),
               type_=sa.Numeric(precision=9, scale=5, asdecimal=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'longitude',
               existing_type=sa.Numeric(precision=9, scale=5, asdecimal=False),
               type_=sa.NUMERIC(precision=5, scale=5),
               existing_nullable=False)
    op.alter_column('city', 'latitude',
               existing_type=sa.Numeric(precision=9, scale=5, asdecimal=False),
               type_=sa.NUMERIC(precision=5, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###
